# Generated by Django 5.0 on 2025-09-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(default='Remote', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pay_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pay_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pay_type', models.CharField(choices=[('annual', 'Annual'), ('hourly', 'Hourly'), ('monthly', 'Monthly')], default='annual', max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='job_images/')),
            ],
        ),
    ]
