# Generated by Django 5.0 on 2025-10-17 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("visa_sponsorship", models.BooleanField(default=False)),
                ("location", models.CharField(default="Remote", max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "pay_min",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pay_max",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pay_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual"),
                            ("hourly", "Hourly"),
                            ("monthly", "Monthly"),
                        ],
                        default="annual",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="job_images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recruiter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="accounts.recruiterprofile",
                    ),
                ),
                (
                    "preferred_skills",
                    models.ManyToManyField(
                        blank=True, related_name="jobs_preferring", to="jobs.skill"
                    ),
                ),
                (
                    "required_skills",
                    models.ManyToManyField(
                        blank=True, related_name="jobs_requiring", to="jobs.skill"
                    ),
                ),
            ],
        ),
    ]
