# Generated by Django 5.0 on 2025-09-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pay', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='job_images/')),
            ],
        ),
    ]
