# Generated by Django 5.0 on 2025-09-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_pay_job_company_job_pay_max_job_pay_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Remote', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='pay_type',
            field=models.CharField(choices=[('annual', 'Annual'), ('hourly', 'Hourly'), ('monthly', 'Monthly')], default='annual', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=255),
        ),
    ]
