# Generated by Django 5.0 on 2025-10-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobSeekerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=255)),
                ("education", models.TextField(blank=True)),
                ("work_experience", models.TextField(blank=True)),
                ("links", models.URLField(blank=True, null=True)),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("public", "Visible to All Employers and Job Seekers"),
                            ("employers_only", "Visible to Employers Only"),
                            ("private", "Visible to Me Only"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("projects", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecruiterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "company",
                    models.CharField(default="Sole Proprietorship", max_length=255),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
